services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: main_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  test_db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"
    volumes:
      - test_postgres_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - test_db
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/main_db
      DATABASE_TEST_URL: postgresql+asyncpg://postgres:postgres@test_db:5432/test_db

volumes:
  postgres_data:
  test_postgres_data:
